services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    network_mode: "host"
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost-d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html  
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: 1

  acme-companion:
    image: nginxproxy/acme-companion
    network_mode: "host"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      nginx-proxy:
        condition: service_started     
    container_name: acme-companion
    volumes_from:
      - nginx-proxy
    volumes:      
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=aaron@atalma.io      
      - NGINX_PROXY_CONTAINER=nginx-proxy      
      - DEBUG=1           

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    network_mode: host
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_SERVER_HTTP_PORT: 3000
      GF_GITHUB_PLUGINS: "https://github.com/grafana/grafana-infinity-datasource/releases/download/v2.11.4/yesoreyeram-infinity-datasource-2.11.4.zip"
      PROMETHEUS_URL: "http://${PROMETHEUS_TARGET:-localhost:9090}"
      ALERTMANAGER_URL: "http://${ALERTMANAGER_TARGET:-localhost:9093}"
      WALRUS_NODE_TARGET: ${WALRUS_NODE_TARGET:-}
      WALRUS_AGGREGATOR_TARGET: ${WALRUS_AGGREGATOR_TARGET:-}
      WALRUS_PUBLISHER_TARGET: ${WALRUS_PUBLISHER_TARGET:-}
      WALRUS_NODE_URL: ${WALRUS_NODE_URL:-}
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: monitor.testnet.walrus.atalma.io
      LETSENCRYPT_HOST: monitor.testnet.walrus.atalma.io
      LETSENCRYPT_EMAIL: aaron@atalma.io   
      LETSENCRYPT_SINGLE_DOMAIN_CERTS: true
    volumes:
      - ./grafana/dashboards:/tmp/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: 1

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: host
    command:
      - '--web.listen-address=:${PROMETHEUS_PORT:-9090}'
    volumes:
      - prometheus:/prometheus
      - ./prometheus/entrypoint.sh:/entrypoint.sh
      - ./prometheus/rules:/etc/prometheus/rules
    environment:
      PROMETHEUS_TARGET: ${PROMETHEUS_TARGET:-localhost:9090}
      WALRUS_NODE_TARGET: ${WALRUS_NODE_TARGET:-}
      WALRUS_AGGREGATOR_TARGET: ${WALRUS_AGGREGATOR_TARGET:-}
      WALRUS_PUBLISHER_TARGET: ${WALRUS_PUBLISHER_TARGET:-}
      ALERTMANAGER_TARGET: ${ALERTMANAGER_TARGET:-localhost:9093}
    entrypoint: ["/entrypoint.sh"]
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: 1

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    command:
      - '--web.listen-address=:${ALERTMANAGER_PORT:-9093}'
      - '--cluster.listen-address='
    volumes:
      - ./alertmanager/entrypoint.sh:/entrypoint.sh
    network_mode: "host"
    environment:
      ALERTMANAGER_DEFAULT_WEBHOOK_PORT: "${ALERTMANAGER_DEFAULT_WEBHOOK_PORT:-3001}"
      PAGERDUTY_INTEGRATION_KEY: "${PAGERDUTY_INTEGRATION_KEY:-}"
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN:-}"
      TELEGRAM_CHAT_ID: "${TELEGRAM_CHAT_ID:-}"
      DISCORD_WEBHOOK_URL: "${DISCORD_WEBHOOK_URL:-}"
    entrypoint: ["/entrypoint.sh"]
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: 1

  walrus-aggregator:
    build:
      context: .
      dockerfile: Dockerfile.walrus-aggregator
      network: host
    network_mode: "host"
    dns:
      - 8.8.8.8
      - 8.8.4.4      
    volumes:
      - /opt/walrus-aggregator:/opt/walrus
    container_name: walrus-aggregator
    restart: unless-stopped
    environment:
      VIRTUAL_PORT: 9000
      VIRTUAL_HOST: aggregator.testnet.walrus.atalma.io
      LETSENCRYPT_HOST: aggregator.testnet.walrus.atalma.io
      LETSENCRYPT_EMAIL: aaron@atalma.io
      LETSENCRYPT_SINGLE_DOMAIN_CERTS: true
    ports:
      - "9000:9000"
      - "27182:27182"
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: 1            

volumes:
  prometheus:
    driver: local
  grafana:
    driver: local
  certs:
  vhost-d:
  html:
  acme:

networks:
  proxy:
    driver: bridge
  internal:
    driver: bridge            
